### ISSUE TITLE
服务级注册到nacos时指定namespace没有效果

### ISSUE THREAD

**Issue by qtsj1997** [apache/dubbo-go#1544]
### 配置内容
```yaml
dubbo:
  registries:
    demoZK:
      protocol: nacos
      address: 127.0.0.1:8848
      registry-type: service
      username: nacos
      password: nacos
      timeout: 20s
      namespace: test
      group: test
  metadata-report:
    protocol: nacos
    address: 127.0.0.1:8848
  protocols:
    triple:
      name: tri
      port: 20000
    dubbo:
      name: dubbo
      port: 20001
    params:
      username: nacos
      password: nacos
  provider:
    registryIDs:
      - demoZK
    services:
      GreeterProvider:
        protocolIDs: triple
        interface: com.apache.dubbo.sample.basic.IGreeter
 ```

### 注册结果

![image](https://user-images.githubusercontent.com/50602333/139174945-3d3a9125-3c1f-4721-baea-c5be965991d6.png)

想要注册到设定的test名称空间，但是指定的namespace和group都没有效果

版本
dubbo.apache.org/dubbo-go/v3 v3.0.0-rc2.0.20211026020634-a45fd29e8a6d
