### ISSUE TITLE
配置中心设置的 namespace 不生效

### ISSUE THREAD

**Issue by wwek** [apache/dubbo-go#1573]
**What happened**:
1、config-center 配置的 namespace: dev
![image](https://user-images.githubusercontent.com/1239403/140709874-6c062348-724d-4c7e-93e9-b8b47318cfc5.png)

```
dubbo:
  config-center:
    protocol: nacos
    address: 127.0.0.1:8848
    group: dubbo
    namespace: dev
    data-id: "dubbogo-qznotify.yaml"
    timeout: 10s
    params:
      username: nacos
      password: nacos
```

2、 问题 nacos中取是namespace: public，namespace: dev 未生效
![image](https://user-images.githubusercontent.com/1239403/140709911-26ff93bc-50cb-4c94-b49a-a4e8575a1833.png)

3、环境和版本
dubbo.apache.org/dubbo-go/v3 v3.0.0-rc3
```
func main() {
	Version()
	config.SetProviderService(&GreeterProvider{})
	if err := config.Load(); err != nil {
		panic(err)
	}
	logger.Infof("Config Center : %s\n", config.GetRootConfig().ConfigCenter.Namespace)
	select {}
}

```

**What you expected to happen**:
应该取设置的namespace: dev  中的
