### ISSUE TITLE
[Proposal] Should we add user defined configuration in dubbogo.yml for 3.0?

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go#1609]
exmaple
```yaml
dubbo:
  registries:
    demoZK:
      protocol:   zookeeper
      address: xxx
  protocols:
    triple:
      name: tri
      port: 20000
  provider:
    services:
      GreeterProvider:
        version: "3.0"
  properties: # add this field
    mysql-address: localhost:3306
    mysql-password: root
    redis-address: localhost:6379
    redis-db: 1
```

User can get property like:
```go
addr := config.GetProperty("mysql-address", "defualt-address")
```
