### ISSUE TITLE
The Protocols on the client config is not working properly.

### ISSUE THREAD

**Issue by justxuewei** [apache/dubbo-go#1666]
**What happened**:

When we use the following config for the consumer, `mydubbo` protocol is not working as expected.

```yaml
dubbo:
  protocols:
    mydubbo:
      name: dubbo
      params:
        tcp-read-timeout: 30s
        tcp-write-timeout: 30s
        wait-timeout: 30s
  registries:
    zk:
      protocol: zookeeper
      address: 127.0.0.1:2181
  consumer:
    registry-ids:
      - zk
    adaptive-service: true
    references:
      Provider:
        protocol: mydubbo
        interface: org.apache.dubbo.Provider
  logger:
    zap-config:
      level: debug
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
