### ISSUE TITLE
nacos+grpc client 启动报错，可以正常访问

### ISSUE THREAD

**Issue by tonyjt** [apache/dubbo-go#1708]
grpc + nacos + custom config

服务端口号：20001

dubbo是自定义的struct

**What happened**:
客户端启动时报错，但是访问正常

![image](https://user-images.githubusercontent.com/1655596/148930845-7a090054-26b5-4244-a88e-aa000fc663f5.png)

**What you expected to happen**:
无报错
**How to reproduce it (as minimally and precisely as possible)**:

配置：

```
  registries: 
    nacosWithCustomGroup:
      protocol: nacos
      timeout: 10s
      address: "test.nacos.com:8848"
      group: dubbo
  consumer:
    references:
      GreeterClientImpl:
        protocol: grpc
        interface: rpc.dubbo.examples.HelloWorldProvider4
```
代码

```
func main() {
	// init rootConfig with config api
	ClientLoad()
	// run rpc invocation
	testSayHello()
}

func testSayHello() {
	ctx := context.Background()

	req := pb.HelloRequest{
		Name: "laurence",
	}
	user, err := grpcGreeterImpl.SayHello(ctx, &req)
	if err != nil {
		log.Error(err, "grpc error")
	}

	logger.Infof("Receive user = %s", user.Message)
	select {}
}

func ClientLoad() {
	var dubbo Dubbo
	config.ConfigGetAndUnmarshal("dubbo", &dubbo)

	fmt.Println(dubbo.Client.Registries)
	rc := dconfig.NewRootConfigBuilder().
		SetConsumer(dubbo.Client.Consumer).
		SetRegistries(dubbo.Client.Registries).
		Build()

	logger.SetLogger(&log.Log{})
	// start dubbo-go framework with configuration
	if err := dconfig.Load(dconfig.WithRootConfig(rc)); err != nil {
		panic(err)
	}
	//dconfig.SetConsumerConfig(dubbo.Client)

}
type Dubbo struct {
	Server *dconfig.RootConfig
	Client *dconfig.RootConfig
}
```
**Anything else we need to know?**:
