### ISSUE TITLE
After running for a period of time, dubbo-getty disconnects the session

### ISSUE THREAD

**Issue by complone** [apache/dubbo-go#1763]
**What happened**:

I based the test case https://github.com/complone/dubbo-go-benchmark/tree/test-dubbo/3.0/adaptivesvc

client/dubbogo.yml
```
dubbo:
  registries:
    demoZK:
      protocol: zookeeper
      address: node1:2181
  consumer:
    references:
      FibProvider:
        protocol: dubbo
        interface: org.apache.dubbo.FibProvider
  logger:
    zap-config:
      level: info
```

server/dubbogo.yml

```
# dubbo server yaml configure file

dubbo:
  registries:
    demoZk:
      protocol: zookeeper
      timeout: 20s
      address: node1:2181
  protocols:
    dubbo:
      name: dubbo
      port: 20002
  provider:
    registry-ids:
      - zk
    #    adaptive-service-verbose: true
    services:
      FibProvider:
        protocol: dubbo
        interface: org.apache.dubbo.FibProvider
#  logger:
#    zap-config:
#      level: debug

```

The stress test based on dubbo-go-benchmark is as follows:

```
TPS 8
PARALLEL 10
DURATION 1m
FUNC_NAME FIBONACCI
FIBONACCI_N 10
FIBONACCI_WORKER_NUM 4
```

After running for 1 minute, the error stack is as follows

```
2022-02-21T21:05:48.257+0800    INFO    client/client.go:60     TPS is set to 8.
2022-02-21T21:05:48.257+0800    INFO    client/client.go:64     Parallel is set to 10.
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
FIBONACCI result: 55
2022-02-21T21:05:48.262+0800    ERROR   dubbo-getty@v1.4.7/session.go:606       {client:TCP_CLIENT:1:192.168.101.227:61918<->192.168.101.227:20002}, [session.conn.read] = error:read tcp 192.168.101.227:61918->192.168.101.227:20002: read: connection reset by peer
github.com/apache/dubbo-getty.(*gettyTCPConn).recv
        /Users/windwheel/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.7/connection.go:282
github.com/apache/dubbo-getty.(*session).handleTCPPackage
        /Users/windwheel/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.7/session.go:647
github.com/apache/dubbo-getty.(*session).handlePackage
        /Users/windwheel/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.7/session.go:606
runtime.goexit
        /opt/homebrew/Cellar/go@1.16/1.16.9/libexec/src/runtime/asm_arm64.s:1130
github.com/apache/dubbo-getty.(*session).handleTCPPackage
        /Users/windwheel/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.7/session.go:665
github.com/apache/dubbo-getty.(*session).handlePackage
        /Users/windwheel/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.7/session.go:606
runtime.goexit
        /opt/homebrew/Cellar/go@1.16/1.16.9/libexec/src/runtime/asm_arm64.s:1130
github.com/apache/dubbo-getty.(*session).handlePackage
        /Users/windwheel/go/pkg/mod/github.com/apache/dubbo-getty@v1.4.7/session.go:606
2022-02-21T21:05:48.262+0800    INFO    dubbo-getty@v1.4.7/session.go:614       {client:TCP_CLIENT:1:192.168.101.227:61918<->192.168.101.227:20002}, [session.handlePackage] gr will exit now, left gr num 0
2022-02-21T21:05:49.258+0800    WARN    proxy/proxy.go:210      [CallProxy] received rpc err: Failed to invoke the method Fibonacci in the service org.apache.dubbo.FibProvider. Tried 1 times of the providers [dubbo://:@192.168.101.227:20002/?interface=org.apache.dubbo.FibProvider&group=&version= dubbo://:@192.168.101.227:20002/?interface=org.apache.dubbo.FibProvider&group=&version=] (2/1)from the registry zookeeper://node1:2181?registry=zookeeper&registry.group=&registry.label=true&registry.namespace=&registry.preferred=false&registry.role=0&registry.timeout=5s&registry.ttl=10s&registry.weight=0&registry.zone=&simplified=false on the consumer 192.168.101.227 using the dubbo version 3.0.0. Last error is session Already Closed.: session Already Closed
```

**What you expected to happen**:

Works fine after running for a while

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
