### ISSUE TITLE
Set hystrix config failed

### ISSUE THREAD

**Issue by tg0428** [apache/dubbo-go#1883]
**What happened**:
After setting the hystrix configuration, a panic error occurred during startup
```
panic: interface conversion: interface {} is map[string]interface {}, not map[interface {}]interface {}

goroutine 42 [running]:
dubbo.apache.org/dubbo-go/v3/filter/hystrix.initConfigConsumer()
        /Users/xxxx/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.1/filter/hystrix/filter.go:254 +0x29b
```

**What you expected to happen**:
The program starts normally and hystrix takes effect

**How to reproduce it (as minimally and precisely as possible)**:
Use this yaml:
```
dubbo:
  consumer:
      filter: hystrix_consumer
      filter-conf:
        hystrix:
          configs:
            Default:
              timeout: 100
              sleep_window: 5
              max_concurrent_requests: 5000
              error_percent_threshold: 1
              request_volume_threshold: 1
          default: "Default"
  references:
      IndexClientImpl:
        protocol: grpc
        interface: com.xxx.index.server
        group: xxx_group
        version: v1.0
        check: false
        retries: 0
        async: true
```

**Anything else we need to know?**: 
dubbo-go v3.0.1

Can u provide a demo configuration of hystrix please?
