### ISSUE TITLE
PrividerConfig.Filter and ReferenceConfig.Filter not work

### ISSUE THREAD

**Issue by ray2011** [apache/dubbo-go#1921]
**What happened**:
server config:
``` yml
dubbo:
  protocols:
    tripleKey:
      name: tri
      port: 20000
  provider:
    filter: tracing
    services:
      UserProvider:
        serialization: gob
        interface: box.research.dubbo.server.UserProvider # must be compatible with grpc or dubbo-java server
```
When start server, filter is the default setting, config not work:

 [Triple Protocol] Export service: tri://:20000/box.research.dubbo.server.UserProvider?accesslog=&app.version=3.0.0&application=dubbo.io&auth=&bean.name=UserProvider&cluster=failover&config.tracing=&environment=dev&execute.limit=&execute.limit.rejected.handler=&export=true&interface=box.research.dubbo.server.UserProvider&loadbalance=random&message_size=4&metadata-type=local&module=sample&name=dubbo.io&organization=dubbo-go&owner=dubbo-go&param.sign=&pid=3091&registry.role=3&release=dubbo-golang-3.0.0&retries=&serialization=gob&**service.filter=echo%2Cmetrics%2Ctoken%2Caccesslog%2Ctps%2Cgeneric_service%2Cexecute%2Cpshutdown**&side=provider&timestamp=1654324473&tps.limit.interval=&tps.limit.rate=&tps.limit.rejected.handler=&tps.limit.strategy=&tps.limiter=&warmup=

client config:
``` yml
dubbo:
  consumer:
    references:
      UserProvider:
        filter: tracing
        protocol: tri
        url: tri://localhost:20000
        serialization: gob
        interface: box.research.dubbo.server.UserProvider # must be compatible with grpc or dubbo-java server
```

When start client, filter is the default setting, config not work:
2022-06-04T14:36:43.689+0800    INFO    dubbo3/dubbo3_protocol.go:141   [Triple Protocol] Refer service: tri://localhost:20000/box.research.dubbo.server.UserProvider?app.version=3.0.0&application=dubbo.io&async=false&bean.name=UserProvider&cluster=failover&config.tracing=&environment=dev&generic=&group=&interface=box.research.dubbo.server.UserProvider&loadbalance=&metadata-type=local&module=sample&name=dubbo.io&organization=dubbo-go&owner=dubbo-go&provided-by=&**reference.filter=cshutdown**&registry.role=0&release=dubbo-golang-3.0.0&retries=&serialization=gob&side=consumer&sticky=false&timestamp=1654324603&version=

**What you expected to happen**:
2022-06-04T14:41:28.733+0800    INFO    dubbo3/dubbo3_protocol.go:81    [Triple Protocol] Export service: tri://:20000/box.research.dubbo.server.UserProvider?accesslog=&app.version=&application=dubbo.io&auth=&bean.name=UserProvider&cluster=failover&config.tracing=&environment=&execute.limit=&execute.limit.rejected.handler=&export=true&interface=box.research.dubbo.server.UserProvider&loadbalance=random&message_size=4&metadata-type=local&module=sample&name=dubbo.io&organization=dubbo-go&owner=dubbo-go&param.sign=&pid=4844&registry.role=3&release=dubbo-golang-3.0.0&retries=&serialization=gob&**service.filter=tracing**&side=provider&timestamp=1654324888&tps.limit.interval=&tps.limit.rate=&tps.limit.rejected.handler=&tps.limit.strategy=&tps.limiter=&warmup=

2022-06-04T14:42:37.272+0800    INFO    dubbo3/dubbo3_protocol.go:141   [Triple Protocol] Refer service: tri://localhost:20000/box.research.dubbo.server.UserProvider?app.version=&application=dubbo.io&async=false&bean.name=UserProvider&cluster=failover&config.tracing=&environment=&generic=&group=&interface=box.research.dubbo.server.UserProvider&loadbalance=&metadata-type=local&module=sample&name=dubbo.io&organization=dubbo-go&owner=dubbo-go&provided-by=&**reference.filter=cshutdown%2Ctracing**&registry.role=0&release=dubbo-golang-3.0.0&retries=&serialization=gob&side=consumer&sticky=false&timestamp=1654324957&version=

Filter config should work.

**How to reproduce it (as minimally and precisely as possible)**:
Add Filter config such as above in latest dubbo-go.
