### ISSUE TITLE
service-discovery-registry failed when set application config

### ISSUE THREAD

**Issue by ray2011** [apache/dubbo-go#1925]
**What happened**:
server config:
``` yml
dubbo:
  application:
    organization: "dubbo"
    name: "game"
    module: "dubbo-go game server"
    version: "0.0.1"
    environment: "dev"
  registries:
    etcd:
      protocol: "etcdv3"
      timeout: "3s"
      address: "127.0.0.1:2379"
      registry-type: service
  metadata-report:
    protocol: etcdv3
    address: 127.0.0.1:2379
  protocols:
    triple:
      name: tri
      port: 20000
  provider:
    services:
      GreeterProvider:
        interface: com.apache.dubbo.sample.basic.IGreeter # must be compatible with grpc or dubbo-java

```

client config:
``` yml
dubbo:
  application:
    organization: "dubbo"
    name: "game"
    module: "dubbo-go game server"
    version: "0.0.1"
    environment: "dev"
  registries:
    etcd:
      protocol: "etcdv3"
      timeout: "3s"
      address: "127.0.0.1:2379"
      registry-type: service
  metadata-report:
    protocol: etcdv3
    address: 127.0.0.1:2379
  protocols:
    triple:
      name: tri
      port: 20000
  provider:
    services:
      GreeterProvider:
        interface: com.apache.dubbo.sample.basic.IGreeter # must be compatible with grpc or dubbo-java

```
client log:
> 2022-06-07T19:53:27.378+0800    INFO    config/config_loader_options.go:200     The following profiles are active: default
2022-06-07T19:53:27.378+0800    INFO    config/root_config.go:129       [Config Center] Config center doesn't start
2022-06-07T19:53:27.381+0800    WARN    prometheus/reporter.go:237      new prometheus reporter with error = listen tcp :9090: bind: address already in use
2022-06-07T19:53:27.381+0800    INFO    etcdv3/service_discovery.go:310 etcd address is: 127.0.0.1:2379,timeout is:3s
2022-06-07T19:53:27.387+0800    INFO    dubbo/dubbo_protocol.go:98      [DUBBO Protocol] Refer service: dubbo://172.22.28.48:38983/org.apache.dubbo.metadata.Metada
taService?application=game&group=game&interface=org.apache.dubbo.metadata.MetadataService&port=38983&protocol=dubbo&release=dubbo-golang-3.0.0&timestamp=1654602800
&version=1.0.0
2022-06-07T19:53:27.387+0800    INFO    etcdv3/listener.go:204  got children list key -> /services/game/172.22.28.48:20000
2022-06-07T19:53:27.387+0800    INFO    etcdv3/listener.go:219  [ETCD Listener] listen dubbo service key{/services/game}
2022-06-07T19:53:30.385+0800    ERROR   config/consumer_config.go:157   No provider available of the service com.apache.dubbo.sample.basic.IGreeter.please check co
nfiguration.
dubbo.apache.org/dubbo-go/v3/config.(*ConsumerConfig).Load
        /home/raynor/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.2/config/consumer_config.go:157
dubbo.apache.org/dubbo-go/v3/config.(*RootConfig).Start.func1
        /home/raynor/go/pkg/mod/dubbo.apache.org/dubbo-go/v3@v3.0.2/config/root_config.go:203
sync.(*Once).doSlow
        /home/raynor/sdk/go1.18rc1/src/sync/once.go:68
sync.(*Once).Do

**What you expected to happen**:
expect client call success

**How to reproduce it (as minimally and precisely as possible)**:
reproduce example: https://github.com/ray2011/dubbo-go-samples

**Anything else we need to know?**:
