### ISSUE TITLE
Can I add a cutom parameter when registering a dubbo service provider like Java?

### ISSUE THREAD

**Issue by zhaohuabing** [apache/dubbo-go#1936]
In Java, we can add some custom parameters like this:
 
 ```
  <dubbo:application name="dubbo-sample-provider">
      <dubbo:parameter key="custom_parameter1" value="${CUSTOM_PARAMETER1}" />
      <dubbo:parameter key="custom_parameter2" value="${CUSTOM_PARAMETER2}" />
      <dubbo:parameter key="custom_parameter3" value="${CUSTOM_PARAMETER3}" />
</dubbo:application>
```
    
  Can I achieve this in dubbo-go, and how?
  
  Thanks!

**Comment by sanxun0325** [comment]
example:
**define custom parameters in dubbogo.yml**
```go
dubbo:
  application:
  ......
  registries:
  ......
  custom:
    config-map:
      key: value
```
**get custom parameters**
```go
value := config.GetRootConfig().Custom.GetDefineValue("key", "default_value")
```

**Comment by zhaohuabing** [comment]
@sanxun0325 Thanks. But it seems that the custom parameters won't be put in the registered service instances.

The Java xml configuration in my issue will result the below service registration data in ZK, which is what I want to achieve in dubbo-go.

```
/dubbo/org.apache.dubbo.samples.basic.api.Demoservice/providers/dubbo://10.66.36.160:29527/org.apache.dubbo.samples.basic.api.Demoservice?release=dubbo-golang-3.0.0&timestamp=1655282877& custom_parameter1=foo&custom_parameter1=bar
```

**Comment by sanxun0325** [comment]
@zhaohuabing  Maybe this is what you want 
```
 provider:
    services:
      UserProvider:
        interface: org.apache.dubbo.UserProvider.Test
        params:
          key: value
```

**Comment by zhaohuabing** [comment]
@sanxun0325 Thanks a lot. It worked. Can I use environment variables in the value? Like:

```
dubbo:
  application:
  registries:
  protocols:
  provider:
    services:
      UserProvider:
        interface: org.apache.dubbo.UserProvider.Test
        params:
          custom_parameter1: ${CUSTOM_PARAMETER1}
```
