### ISSUE TITLE
common.MergeURL占用内存一直上升

### ISSUE THREAD

**Issue by fubug** [apache/dubbo-go#2031]
![pprof001 (1)](https://user-images.githubusercontent.com/18571911/186595185-33a395eb-2276-48f3-b2ed-8ae909ef0cc7.svg)
![image](https://user-images.githubusercontent.com/18571911/186595287-07d41ec8-6cda-4ad9-9cca-c0657f56bd45.png)
![image](https://user-images.githubusercontent.com/18571911/186600442-701ebd2b-fe72-4ffb-927b-170564af67bc.png)

**Comment by zhaoyunxing92** [comment]
@彭笳鑫

**Comment by baerwang** [comment]
```go
func MergeURL(serviceURL *URL, referenceURL *URL) *URL {
	// After Clone, it is a new URL that there is no thread safe issue.
	mergedURL := serviceURL.Clone()
	// iterator the referenceURL if serviceURL not have the key ,merge in
	// referenceURL usually will not changed. so change RangeParams to GetParams to avoid the string value copy.// Group get group
	for key, value := range referenceURL.GetParams() {
		if _, ok := mergedURL.GetNonDefaultParam(key); !ok {
			if len(value) > 0 {
				mergedURL.params[key] = value
			}
		}
	}

	// loadBalance,cluster,retries strategy config
	methodConfigMergeFcn := mergeNormalParam(mergedURL.params, referenceURL, []string{constant.LoadbalanceKey, constant.ClusterKey, constant.RetriesKey, constant.TimeoutKey})

	// remote timestamp
	if v, ok := serviceURL.GetNonDefaultParam(constant.TimestampKey); !ok {
		mergedURL.params[constant.RemoteTimestampKey] = []string{v}
		mergedURL.params[constant.TimestampKey] = []string{referenceURL.GetParam(constant.TimestampKey, "")}
	}

	// finally execute methodConfigMergeFcn
	for _, method := range referenceURL.Methods {
		for _, fcn := range methodConfigMergeFcn {
			fcn("methods." + method)
		}
	}
	// In this way, we will raise some performance.
	return mergedURL
}
```

**Comment by Lvnszn** [comment]
疯狂调用 MergeURL这个函数的确会内存上升，细节在定位

**Comment by georgehao** [comment]
发个复现步骤

**Comment by georgehao** [comment]
目前是有内存泄露的问题吗，其实上面那个图和top其实说明不了啥问题，如果有内存泄露的情况，发个复现步骤吧

**Comment by georgehao** [comment]
如果可以的话，发一下内存的增长的截图。如果有条件的发下 内存 diff profile的log

```
curl -s http://127.0.0.1:8080/debug/pprof/heap > 1231.heap
过 一段时间 (5m, 10m, 30m, 1h)
curl -s http://127.0.0.1:8080/debug/pprof/heap > 1241.heap
go tool pprof --http :9090 --base 1231.heap  1241.heap
```

**Comment by fubug** [comment]
截图失真比较严重，辛苦下载下来看下吧https://github.com/fubug/go/blob/main/start%20inuse_space.html

**Comment by fubug** [comment]
> 目前是有内存泄露的问题吗，其实上面那个图和top其实说明不了啥问题，如果有内存泄露的情况，发个复现步骤吧

稍等，我花时间整理个最小版本的代码

**Comment by Lvnszn** [comment]
初步怀疑推送风暴，可以提供注册中心的推送日志么？
集群规模大概是多少？

**Comment by Lvnszn** [comment]
目前怀疑跟多 zk 有关，这边用户把注册中心切换成 nacos 之后看着正常。 有类似问题的可以先切换试试。 root cause 我在跟一下

**Comment by shenchao861129** [comment]
我们目前也遇到了同样的问题。

![image](https://user-images.githubusercontent.com/834323/202430430-1129c518-bc39-40be-89f9-c588910ac3b5.png)


环境：
dubbo-go: v3.0.1
ZooKeeper: v3.4.8

**Comment by mengccmumu** [comment]
这个问题还没有修复吗？？调用链，config.Load->refConfig.Refer->common.MergeURL，没有调用很多次，咋来的内存溢出

**Comment by Lvnszn** [comment]
> 这个问题还没有修复吗？？调用链，config.Load->refConfig.Refer->common.MergeURL，没有调用很多次，咋来的内存溢出


平常状态下比较难复现，你也是 go 调用 java 么？

**Comment by mengccmumu** [comment]
> 

go调java，我这边是可以复现的，直接用jmeter压测，内存很快就涨上来；

**Comment by mengccmumu** [comment]
```
dubbo:
  registries:
    demoZK: # 定义服务注册发现中心
      protocol: zookeeper
      address: x.x.x.x:2181
    demoZK2: # 定义服务注册发现中心
      protocol: zookeeper
      address: x.x.x.x:2182
    demoZK3: # 定义服务注册发现中心
      protocol: zookeeper
      address: x.x.x.x:2183
  consumer:
    references:
      AbcService: # 存根类名
        registry: demoZK,demoZK2,demoZK3
        protocol: dubbo # dubbo 协议，默认 hessian2 序列化方式
        interface: com.asiainno.uplive.riskcontrol.service.AbcService # 接口需要与 go/java 客户端对应
```

**Comment by mengccmumu** [comment]
这是我的配置文件
```
dubbo:
  registries:
    demoZK: # 定义服务注册发现中心
      protocol: zookeeper
      address: x.x.x.x:2181
    demoZK2: # 定义服务注册发现中心
      protocol: zookeeper
      address: x.x.x.x:2182
    demoZK3: # 定义服务注册发现中心
      protocol: zookeeper
      address: x.x.x.x:2183
  consumer:
    references:
      AbcService: # 存根类名
        registry: demoZK,demoZK2,demoZK3
        protocol: dubbo # dubbo 协议，默认 hessian2 序列化方式
        interface: com.xx.xx.xx.AbcService # 接口需要与 go/java 客户端对应
```
