### ISSUE TITLE
使用 Nacos 同一命名空间时，如果通过应用级服务发现调用其他服务接口，无法同时做到提供使用接口级服务发现的 service

### ISSUE THREAD

**Issue by sinfon** [apache/dubbo-go#2044]
定义两个 Nacos 注册中心配置 A 和 B，区别在于 A 的 registry-type 为 service

定义 reference 使用 A，而定义 service 使用 B

---

Dubbo 配置加载启动会按照 Consumer、Provider 的顺序

```
rc.Consumer.Load()
rc.Provider.Load()
```

Consumer 加载时，会按照 `registryUrl.Location` 缓存一个 ServiceDiscoveryRegistry，而在这之后 Provider 加载时，问题场景下，因为 `registryUrl.Location` 相同，会找到并使用这个 registry.Registry，导致实际想要得到的 NacosRegistry 无法加载

```
func (proto *registryProtocol) getRegistry(registryUrl *common.URL) registry.Registry {
        var err error
        reg, loaded := proto.registries.Load(registryUrl.Location)
        if !loaded {
                reg, err = extension.GetRegistry(registryUrl.Protocol, registryUrl)
                if err != nil {
                        logger.Errorf("Registry can not connect success, program is going to panic.Error message is %s", err.Error())
                        panic(err)
                }
                proto.registries.Store(registryUrl.Location, reg)
        }
        return reg.(registry.Registry)
}
```

**Comment by binbin0325** [comment]
```yaml
dubbo:
  application:
    name: shield
  registries:
    interface-nacos:
      protocol: nacos
      address: 127.0.0.1:18848
      username: my-test
      password: 123456
      namespace: my-ns
      group: dubbo
      params:
        nacos.logLevel: warn
    service-nacos:
      protocol: nacos
      address: 127.0.0.1:18848
      username: my-test
      password: 123456
      namespace: my-ns
      group: DEFAULT_GROUP
      # 指定该注册中心为：应用级服务发现（service），不填默认为接口级
      registry-type: service
      params:
        nacos.logLevel: warn
  protocols:
    triple:
      name: tri
      port: 20001
  provider:
    services:
      ShieldProvider:
        registry-ids: interface-nacos
        interface: top.sinfon.shield.ShieldApi
        version: v1.0.0
  consumer:
    references:
      SwordApiClientImpl:
        registry-ids: service-nacos
        protocol: tri
        version: 1.0.0
        interface: top.sinfon.sword.SwordApi
        provided_by: sword-service

```
