### ISSUE TITLE
Application interface configuration, consumers can also get providers from other groups by configuring one group.

### ISSUE THREAD

**Issue by bakineW** [apache/dubbo-go#2218]
**What happened**:

Consumers can also get providers from other groups by configuring one group.

**What you expected to happen**:

Configure some different provider metadata-report group values

**How to reproduce it (as minimally and precisely as possible)**:

dubbo-go-samples-master  project

**Anything else we need to know?**:

Application interface config; 
dubbogo 3.0.5 ; 
zookeeper Metadata Center and zookeeper  Registration Center；

**Comment by justxuewei** [comment]
应用级配置后没有分组功能了，我配置了多个提供者他们的分别在配置不同的group，消费着配置了其中一个group却可以拿到所有的提供者并且能调用成功。接口级是有分组效果。

**Comment by bakineW** [comment]
```yaml
###提供者配置
dubbo:
  application:
    name: myapp
    module: opensource
    group: TEST_GROUP
    organization: dubbo
    owner: laurence
    version: 2.0.1
    environment: develop
    metadata-type: remote
  registries:
    demoZK:
      protocol: zookeeper
	  address: 127.0.0.1:32355
      timeout: 3s
      registry-type: service
  metadata-report:
    protocol: zookeeper
	address: 127.0.0.1:32355
    # group: TEST_GROUP  # 改在这里注册路径有改变但也是没效果
  protocols:
    dubbo:
      name: dubbo
      port: 32323
      params:
        session-number: 700
        session-timeout: 180s
        getty-session-param:
          compress-encoding: false
          tcp-no-delay: true
          tcp-keep-alive: true
          keep-alive-period: 120s
          tcp-r-buf-size: 262144
          tcp-w-buf-size: 65536
          tcp-read-timeout: 10s
          tcp-write-timeout: 5s
          wait-timeout: 1s
          max-msg-len: 1024000
          session-name: server
  provider:
    services:
      PiaoProvider:
        interface: com.hw.tool.dubbo.api.service.PiaoProvider
        version: 1.2.3
  logger:
    zap-config:
      level: error
    lumberjack-config:
      maxSize: 1
      maxAge: 3
      maxBackups: 5
      localTime: true
      compress: false
```

**Comment by bakineW** [comment]
```yaml
### 消费者配置
dubbo:
  registries:
    demoZK:
      protocol: zookeeper
      timeout: 3s
      address: 127.0.0.1:32355
      registry-type: service
  metadata-report:
    protocol: zookeeper
    address: 127.0.0.1:32355
  consumer:
    registry-ids:
      - demoZK
    references:
      PiaoProvider:
        protocol: dubbo
        # provided_by: myApp
        interface: com.hw.tool.dubbo.api.service.PiaoProvider
        version: 1.2.3
        group: DEV_GROUP # TEST_GROUP
        cluster: failover
        loadbalance: mybalance
        methods:
          - name: "PiaoStart"
            timeout: 15s
  protocols:
    dubbo:
      name: dubbo
      params:
        session-timeout: 180s
        getty-session-param:
          compress-encoding: false
          tcp-no-delay: true
          tcp-keep-alive: true
          keep-alive-period: 180s
          tcp-r-buf-size: 262144
          tcp-w-buf-size: 65536
          tcp-read-timeout: 1s
          tcp-write-timeout: 5s
          wait-timeout: 1s
          max-msg-len: 1024000
          session-name: client
  logger:
    zap-config:
      level: debug
    lumberjack-config:
      filename: ./dlog/logs.log
      maxSize: 1
      maxAge: 3
      maxBackups: 5
      localTime: true
      compress: false
```
