### ISSUE TITLE
Support direct connecting to endpoint with xds protocol

### ISSUE THREAD

**Issue by WesleyWu** [apache/dubbo-go#2342]
**What would you like to be added**:
支持像 grpc 官方示例中的直连 xds 协议的 endpoint
https://github.com/grpc/grpc-go/blob/master/examples/features/xds/client/main.go

例如这样的配置文件：
```
dubbo:
  consumer:
    references:
      GreeterClientImpl:
        url: xds:///dubbogo-helloworld:20000
        protocol: tri
```

**Why is this needed**:
我在GKE中部署了 dubbo-go 的 provider 服务端，并且使用了GCP Traffic Director来提供 proxyless 的 service mesh。
实测，通过 python 的 grpc 客户端，以及 [grpc-go官方示例](https://github.com/grpc/grpc-go/blob/master/examples/features/xds/client/main.go) ，都可以正常通过
`xds:///dubbogo-helloworld:20000` 这样的 endpoint 调用 provider 的 rpc 方法。

但不知道怎么配置dubbo-go 的客户端这么做。

注意：使用了GCP Traffic Director做proxyless服务网格，就不再需要上报服务到注册中心，客户端也不需要通过注册中心来获取具体的服务端点，而是通过支持xds协议的 `xds:///dubbogo-helloworld:20000` 来获取服务端点（可实现自动负载均衡）。
