### ISSUE TITLE
Prometheus reporter always listen 9090 ignore config file.

### ISSUE THREAD

**Issue by ev1lQuark** [apache/dubbo-go#2361]
### Environment

- Server: Dubbo-go, main branch
- Client: Dubbo-go, main branch
- Protocol: Triple
- Registry: zk

### Issue description
Metrics module starts reporter twice.
- https://github.com/apache/dubbo-go/blob/10336a56ba41642e9c081da566f762ff06ece760/config/metric_config.go#L71
- https://github.com/apache/dubbo-go/blob/10336a56ba41642e9c081da566f762ff06ece760/filter/metrics/filter.go#L77

The first time during config loading, Prometheus reporter tries to listening 9091 in expect. (9091 is set in config file)
The second time during filter init, Prometheus reporter tries to listen 9090 as the default value.

### Logs

<details><summary>Click me to check logs</summary>

```
2023-07-19 14:58:16     WARN    prometheus/reporter.go:94       new prometheus reporter with error = listen tcp :9090: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
```

</details>

### Config File

<details><summary>Click me to check files</summary>

```
dubbo:
  application:
    version: 3.0.1
  metrics:
    enable: true # default is true
    path: /metrics # default is /metrics
    summary-max-age: 60000000000 # 1 minute, default is 10min
    port: 9091 # default is 9090
  registries:
    myzk:
      protocol: zookeeper
      address: localhost:2181
  protocols:
    triple:
      name: tri
      port: 20000
  logger:
    zap-config:
      level: debug
  provider:
    services:
      GreeterProvider:
        group: dubbo-go
```

</details>
