### ISSUE TITLE
Simplify configuration when enable metrics module

### ISSUE THREAD

**Issue by ev1lQuark** [apache/dubbo-go#2407]
There have been many changes in the Metrics module recently, try not to modify the configuration file to affect users. However, currently enabling the metrics capability on the consumer side requires modifying two places in the configuration file at the same time:
- metrics.enable: true
- consumer.filter: metrics

Like [this](https://github.com/apache/dubbo-go-samples/blob/7cce362a5dcb7770d9220c7682238c2643c46eb4/metrics/go-client/conf/dubbogo.yml):
```yaml
dubbo:
  application:
    version: 3.0.1
  metrics:
    enable: true # default is true
    path: /metrics # default is /metrics
    summary-max-age: 60000000000 # 1 minute, default is 10min
    port: 9092 # default is 9090
  registries:
    demoZK:
      protocol: zookeeper
      timeout: 3s
      address: 127.0.0.1:2181
  consumer:
    references:
      GreeterClientImpl:
        group: dubbo-go
    filter: metrics
```

To make matters worse, the corresponding provider side does not need to display the metrics filter. 

Like [this](https://github.com/apache/dubbo-go-samples/blob/7cce362a5dcb7770d9220c7682238c2643c46eb4/metrics/go-server/conf/dubbogo.yml):
```yaml
dubbo:
  application:
    version: 3.0.1
  metrics:
    enable: true # default is true
    path: /metrics # default is /metrics
    summary-max-age: 60000000000 # 1 minute, default is 10min
    port: 9091 # default is 9090
  registries:
    myzk:
      protocol: zookeeper
      address: localhost:2181
  protocols:
    triple:
      name: tri
      port: 20000
  logger:
    zap-config:
      level: debug
  provider:
    services:
      GreeterProvider:
        group: dubbo-go
```

I think `metrics.enable: true` should be the only condition to enable or disable metrics module.
