### ISSUE TITLE
dubbo-go metric 设计文档

### ISSUE THREAD

**Issue by FoghostCn** [apache/dubbo-go#2411]
大纲：
概述
使用方式
实现原理
代码结构与原理
基础qps指标
三大中心
本地聚合
指标暴漏
指标推送

**Comment by FoghostCn** [comment]
### 使用方式
开启 metric 指标采集只需要在YAML配置文件中开启相应开关：
```yaml
metrics:
  enable: true # default is false
  path: /custom-metrics-path # default is /metrics
  port: 9092 # default is 9090
```
编码方式开启 metric：
```go
rootConfig := config.NewRootConfigBuilder().
  SetProvider(config.NewProviderConfigBuilder().
    AddService("GreeterProvider", config.NewServiceConfigBuilder().Build()).Build()).
    SetMetric(config.NewMetricConfigBuilder().
      SetEnable(true). // 使用默认配置只需开启开关即可
      SetProrocol("prometheus").
      SetPath("/metric").
      SetPort(9092).
    Build()).
  Build()
```
默认使用 Prometheus pull 模式暴露指标数据。
