### ISSUE TITLE
panic config /reference_config.go line 105 

### ISSUE THREAD

**Issue by ijustyce** [apache/dubbo-go#2439]
Code show as below, consumer field is a pointer so may be nil.

<img width="532" alt="image" src="https://github.com/apache/dubbo-go/assets/6041166/8ae0b30e-e36a-4c2e-bbe6-69cb463feac1">

**Comment by DMwangnima** [comment]
@ijustyce ReferenceConfig must be defined within ConsumerConfig, as this dubbogo.yml shows:
```yaml
dubbo:
  registries:
    demoZK:
      protocol: zookeeper
      timeout: 3s
      address: 127.0.0.1:2181
  consumer:
    references:
      GreeterClientImpl:
        protocol: tri
        interface: com.apache.dubbo.sample.basic.IGreeter
```
**ReferenceConfig.Init()** is invoked by **ConsumerConfig.Init()**. As a result, there is no problem with nil pointer.
