### ISSUE TITLE
dubbo-go@v3.1.0获取不到nacos配置

### ISSUE THREAD

**Issue by saber72237** [apache/dubbo-go#2580]
### Environment

- Client: Dubbo-go, v3.1.0
- Protocol: Triple
- Registry: Nacos, v2.3.0

### Issue description

```
 func InitDubbo(moduleName, environmentName, groupName, nacosUrl, nameSpace string, nacosPort int) {
	dataId := fmt.Sprintf("%s-%s", moduleName, environmentName)
	nacosAddress := fmt.Sprintf("%s:%d", nacosUrl, nacosPort)
	initProvider()
	//initConsumer()
	rootConfig := config.NewRootConfigBuilder().
		SetConfigCenter(config.NewConfigCenterConfigBuilder().
			SetProtocol("nacos").SetAddress(nacosAddress).SetNamespace(nameSpace).
			SetDataID(dataId).SetGroup(groupName).
			Build()).
		Build()
	if err := config.Load(config.WithRootConfig(rootConfig)); err != nil {
		panic("Init Dubbo Error Please Check Config")
	}
}
```

```
dubbo:
  application:
    name: file
    module: file
    organization:
    owner:
    version: 1.0
    environment: dev
  registries:
    nacosWithCustomGroup:
      protocol: nacos
      address: 192.168.0.8:8848
      group: dubbo
      registry-type: interface
      namespace: public
  protocols:
    triple:
      name: tri
      port: 22000
      max-server-send-msg-size: 100mib
      max-server-recv-msg-size: 100mib
  provider:
    services:
```

### Logs

<details><summary>Click me to check logs</summary>

```
2024-01-15 21:35:39     WARN    config/config_center_config.go:150      [Config Center] Dynamic config center has started, but got empty config with config-center configuration &{Protocol:nacos Address:119.12.161.195:8848 DataId:file-dev Cluster: Group:dubbo Username: Password: Namespace:public AppID:dubbo Timeout:10s Params:map[] FileExtension:yaml}
```

</details>
