### ISSUE TITLE
How tri provider chose the filter?

### ISSUE THREAD

**Issue by yumosx** [apache/dubbo-go#2789]
在尝试修复 #2670 这个问题的时候, 我发现如果 provider 的名字是 tri 的话, 会创建两个新的 service 一个叫做 heath service 另外一个叫做 reflect svcice, **然后就是对这两个 service 进行初始化**

在初始化的过程中, 如果 service 的 filter 为空 `""` 那么就会使用 provider的 filter 去初始化这两个 service 的 filter, 所以下面这个 yaml 是生效的

```yaml
dubbo:
  registries:
    demoZK:
      protocol: nacos
      timeout: 10s
      address: 127.0.0.1:8848
  protocols:
    tripleProtocol:
      name: tri
      port: 20000
  provider:
    filter: ValidateFilter    
    services:
      GreetTripleServer:
        interface: com.apache.dubbo.sample.Greeter
```

![Image](https://github.com/user-attachments/assets/d441598f-ffb8-4476-93d4-5d33e5293c1d)

但是如果单纯的在 service 层面上定义 filter， 那么 tripleProtocol 的2个服务的 filter 都不会被初始化
```yaml
services:
      GreetTripleServer:
        filter: ValidateFilter
        interface: com.apache.dubbo.sample.Greeter
```

所以我想知道, 如果只是单纯在 services 层面去定义 filter, 那么该如何去初始化 tripleProtocol的两个service的 filter?
1. 是继续去使用 service 的, 但是如果存在多个 service 该怎么办
2. 还是直接报错, 因为 provider.filter 为 " "

主要的源码位于 config/service_config.go 和 provider_config.go

----------------
When trying to fix issue #2670, I found that if the provider is named "tri", two new services would be created: one called "heath service" and another called "reflect service", and then these two services would be initialized.

During the initialization, if the filter of a service is empty "", the filter of the provider would be used to initialize the filters of these two services. So the following YAML configuration would take effect:

However, if a filter is defined at the service level alone, the filters of the two services in tripleProtocol would not be initialized:

So I wonder, if a filter is defined only at the service level, how to initialize the filters of the two services in tripleProtocol?
1. Should it continue to use the service's filter?
2. Or should it just report an error?

The main source code is located in config/service_config.go and provider_config.go.
