### ISSUE TITLE
Enhance: Optimize remotes configuration and constructor

### ISSUE THREAD

**Issue by flycash** [apache/dubbo-go#501]
**What would you like to be added**:

Remotes Configuration.

**Why is this needed**:

Now, there are many implementations based on different middleware, including zookeeper, nacos...
However, we do not have a common way to configure those middleware.
For example, If I want to use the Nacos as registry and configure center, I must configure the Nacos in two different places:

![Nacos as configure center](https://user-images.githubusercontent.com/9923838/80864375-c37d6b80-8cb4-11ea-9512-d2b65ea33c18.png)

![Nacos as registry](https://user-images.githubusercontent.com/9923838/80864385-d55f0e80-8cb4-11ea-8688-5ca43352e833.png)

It's not convenient for users. If the user wants to change the address, he must change all places. 

So I propose that we should define the RemoteConfig, it looks like:
```yml
remotes:
  nacos1:
     address: "1.1.1.1:8080"

registries:
  nacos1:
    protocol: "nacos",
    remoteRef: "nacos1",

config_center:
  protocol: "nacos"
  remoteRef: "nacos1",
```
