### ISSUE TITLE
配置中心下发配置无法实时生效

### ISSUE THREAD

**Issue by whitekeyboard** [apache/dubbo-go#894]
如此示例：
https://github.com/apache/dubbo-go-samples/tree/master/configcenter/nacos/dubbo/go-server
问题一、服务的动态配置，不生效
操作步骤如下：
1、在nacos配置中心，增加DataId为BDTService.configurators，group为dubbo的配置，配置内容如下：
```
scope: application
configVersion: 11.2
enabled: true
configs:
  - type: "general"
    addresses: 
      - "0.0.0.0:20000"
    side: provider
    enabled: true
    parameters:
      cluster: failfast
```
2、启动服务器端，后查看注册的接口的cluster被修改为failfast，再次修改BDTService.configurators的配置，将cluster:failfast修改为failback，发现未生效。

加日志调试看，是第一次获取配置时，代码中默认增加了providerAddresses字段，导致无法load。

问题二，接口的动态配置DataId: com.ikurento.user.UserProvider.configurators, group：dubbo下发上述配置。按照上述配置操作也出现类似的问题。

问题三、当前配置中心下发的配置易用性较差，尤其是上述接口类的配置，还是一步一步扣代码得到的参数，而且部分参数含义理解的也不是很透彻。文档较少，注释也较少。建议可以优化一下配置中心对接的易用性。
