### ISSUE TITLE
lint codes

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go#933]
Add the following codes to github action configure yaml:

```Yaml
    - name: Install go ci lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0

    - name: Run Linter
      run: golangci-lint run --timeout=10m -v --disable-all --enable=govet --enable=staticcheck --enable=ineffassign --enable=misspell
```

Its position should be before go test.

all codes should be checked by golint.
